# Models a POST to a resource, which then redirects to a GET.
---
plugin: rest
resources:
  - path: /static-multi
    contentType: "text/html"
    method: GET
    response:
      statusCode: 200
      headers:
        X-Example: "foo"
      content: |
        <html>
          <head>
            <title>Example</title>
          </head>
          <body>
            Hello, world!
          </body>
        </html>

  - path: /static-multi
    method: POST
    response:
      statusCode: 302
      headers:
        Location: "/static-multi"
