# A static configuration, setting content type, headers, status code and data.
---
plugin: rest
path: /static-single
contentType: "text/html"
method: GET
response:
  statusCode: 200
  headers:
    X-Example: "foo"
  content: |
    <html>
      <head>
        <title>Example</title>
      </head>
      <body>
        Hello, world!
      </body>
    </html>
