plugin: soap
wsdlFile: service.wsdl

resources:
  - binding: SoapBinding
    operation: getPetById
    response:
      # use the value of 'id' from the request message in the response
      template: true
      content: |
        <?xml version="1.0" encoding="UTF-8"?>
        <env:Envelope xmlns:env="http://www.w3.org/2001/12/soap-envelope">
          <env:Header/>
          <env:Body>
            <getPetByIdResponse xmlns="urn:com:example:petstore">
                <id>${context.request.body:!/Envelope/Body/getPetByIdRequest/id}</id>
                <name>Paws</name>
            </getPetByIdResponse>
          </env:Body>
        </env:Envelope>
