plugin: "openapi"
specFile: "openapi3-with-multiple-examples.yaml"

resources:
  - path: /pets/1
    method: get
    response:
      exampleName: catExample

  - path: /pets/2
    method: get
    response:
      exampleName: dogExample

  - path: /pets/3
    method: get
    response:
      file: tortoise.json
      statusCode: 200
