plugin: rest

system:
  stores:
    # this store is preloaded from file
    exampleStore:
      preloadFile: initial-data.json

resources:
  - path: /example
    method: GET
    response:
      content: "Hello ${stores.exampleStore.foo}"
      template: true
