plugin: soap
wsdlFile: service.wsdl

resources:
  - binding: SoapBinding
    operation: getPetById
    requestBody:
      xPath: "/env:Envelope/env:Body/pets:getPetByIdRequest/pets:id"
      value: "10"
      xmlNamespaces:
        env: "http://www.w3.org/2003/05/soap-envelope"
        pets: "urn:com:example:petstore"
    response:
      content: |
        <?xml version="1.0" encoding="UTF-8"?>
        <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
          <env:Header/>
          <env:Body>
            <getPetByIdResponse xmlns="urn:com:example:petstore">
                <id>10</id>
                <name>Whiskers</name>
            </getPetByIdResponse>
          </env:Body>
        </env:Envelope>
