plugin: soap
wsdlFile: petstore.wsdl

resources:
  # return custom response body for a given operation
  - operation: getPetById
    response:
      file: getPetByIdResponse.xml

  # return HTTP 400 response if SOAPAction matches a specific value
  - soapAction: "invalid-pet-action"
    response:
      statusCode: 400
