plugin: soap
wsdlFile: petstore.wsdl

resources:
  - operation: getPetById
    requestBody:
      xPath: //pets:getPetByIdRequest/pets:id
      value: 100
      xmlNamespaces:
        pets: urn:com:example:petstore
    response:
      statusCode: 200
      headers:
        Content-Type: application/xml
      content: |
        <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <pets:getPetByIdResponse xmlns:pets="urn:com:example:petstore">
              <pets:id>100</pets:id>
              <pets:name>dog</pets:name>
            </pets:getPetByIdResponse>
          </soap:Body>
        </soap:Envelope>
