plugin: rest

resources:
# trailing wildcard path match
- method: GET
  path: /*
  response:
    content: "Matched wildcard path"

# exact match takes precedence over wildcard
- method: GET
  path: /exact
  response:
    content: "Matched exact path"
