plugin: rest

resources:
- method: GET
  path: /exact-delay
  response:
    content: "This is a response with a 10s delay"
    # exactly 10s delay
    delay:
      exact: 10000

- method: GET
  path: /range-delay
  response:
    content: "This is a response with a random delay between 5s-15s"
    # delay in range of 500ms-1500ms
    delay:
      min: 5000
      max: 15000
