openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io
paths:
  /pets:
    post:
      summary: Add a new pet
      operationId: addPet
      parameters:
        - in: header
          name: X-CorrelationID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        '201':
          description: Indicates pet added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /pets/{petId}:
    put:
      summary: Update a specific pet
      operationId: updatePet
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        '202':
          description: Indicates pet updated
  /vets:
    get:
      summary: List all veterinarians
      operationId: listVets
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: list of vets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vets"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Vet:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          example: SupaVets
        address:
          $ref: "#/components/schemas/Address"
    Vets:
      type: array
      items:
        $ref: "#/components/schemas/Vet"
    Address:
      type: object
      required:
        - firstLine
        - city
        - postCode
      properties:
        firstLine:
          type: string
          example: 10 Petal Lane
        city:
          type: string
          example: London
        postCode:
          type: string
          example: EC1A 2BC
