plugin: rest

# add a default script file to all resource responses
defaultsFromRootResponse: true
response:
  scriptFile: logger.js

resources:
  - path: /test
    response:
      content: "Hello, world!"
      headers:
        Content-Type: "application/javascript"
