openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io
paths:
  /pets:
    get:
      summary: Get pets
      operationId: getPets
      parameters:
        - name: foo
          in: query
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Indicates pets found
        '204':
          description: Lists pets found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
    post:
      summary: Add a new pet
      operationId: addPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        '201':
          description: Indicates pet added
  /pets/{petId}:
    parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: string
      - name: X-Pet-Username
        in: header
        required: false
        schema:
          type: string
    get:
      summary: Get a specific pet
      operationId: getPetById
      responses:
        '200':
          description: A pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '203':
          description: Non-authoratative pet
        '401':
          description: Unauthorised
    put:
      summary: Update a specific pet
      operationId: updatePet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        '202':
          description: Indicates pet updated
        '409':
          description: Already exists
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
