plugin: rest

system:
  stores:
    # this store is preloaded from inline data
    exampleStore:
      preloadData:
        foo: bar
        baz: { "qux": "corge" }

resources:
  - path: /example
    method: GET
    response:
      content: "Hello ${stores.exampleStore.foo}"
      template: true
